### ISSUE TITLE
enable libitk 5.2 on Windows

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/stir-feedstock#37]
We have run-time errors with libitk 5.2, so it's currently disabled. See https://github.com/conda-forge/stir-feedstock/pull/35 for more information.

**Comment by carterbox** [comment]
Today I learned that you can ask conda-forge to provide you with the broken packages from failed builds by changing a config file. It might help you learn what links are missing with libitk.

https://conda-forge.org/docs/maintainer/conda_forge_yml.html#azure

**Comment by KrisThielemans** [comment]
#53 made this specific to Windows, so I'll change the title

**Comment by KrisThielemans** [comment]
this was done in #61
