### ISSUE TITLE
config dir location in installed version on Windows

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/stir-feedstock#44]
On Windows, the JSON files are in
`%CONDA_PREFIX%\Library\share\stir\config`. Not sure yet where they are on Linux/OSX. If the same, the `activate` scripts will need changing. Of course, then it's a mystery why the tests work with the current scripts on Linux/OSX (but would explain why they don't work for Windows...).

**Comment by ClaireDelplancke** [comment]
I tried the conda installation on macOS 12.0.1.

Output of `stir_config --config-dir` is 
```
Config directory is /Users/cd902/miniconda3/envs/stir5/share/stir/config
You are using STIR 5.0.0
```

Output of `echo $STIR_CONFIG_DIR` is
```
/Users/cd902/miniconda3/envs/stir5/share/stir/config
```

Output of `find $CONDA_PREFIX -name radionuclide_info.json` is
```
/Users/cd902/miniconda3/envs/stir5/share/stir/config/radionuclide_info.json
```

**Comment by KrisThielemans** [comment]
Thanks. I guess that means that stir works fine?

**Comment by ClaireDelplancke** [comment]
Yes it does.
