### ISSUE TITLE
update to 5.1.0

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/stir-feedstock#66]
### Comment:

@hmaarrfk we've release a new version https://github.com/UCL/STIR/releases/tag/rel_5.1.0. I think you hoped that a bot would pick this up and create the `sha256` for us, but nothing's happening for a week now. Do it manually or is there a trick?

**Comment by hmaarrfk** [comment]
fork, manually do it, then issue a PR.

The autotickbot seems to be down. See
https://conda-forge.org/status/

https://github.com/regro/autotick-bot
