### ISSUE TITLE
add CUDA version

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/stir-feedstock#70]
See discussion in https://github.com/conda-forge/parallelproj-feedstock/issues/11

@gschramm, feel like creating a PR?

**Comment by gschramm** [comment]
I will try my best during the next couple of days.

**Comment by gschramm** [comment]
@KrisThielemans I just installed stir 5.1 via conda-forge on my local ubuntu machine that also have cuda.
To my surprise the cuda version of parallelproj got installed. I guess during the builds (didn't check all the build logs),
the cpu version was used.

I guess that means, although the libparallelproh_cuda.so is there, it cannot be used in STIR?
Is there a way to test that?

Georg

**Comment by KrisThielemans** [comment]
We could check the build log (it's fairly close to the top), or you could check include/stir/config.h, or you could run something and check gpu usage. Sorry that there's no easier way

**Comment by gschramm** [comment]
config.h says:
```
/* #undef parallelproj_built_with_CUDA */
```

What does that exactly mean? (I am confused by the /* + negation)

**Comment by KrisThielemans** [comment]
As it's not defined, it means it wasn't built with it.

For instance, the ITK one should be defined

**Comment by gschramm** [comment]
Ok, that makes sense. I will work on the PR later.

**Comment by KrisThielemans** [comment]
@gschramm I've updated my Windows 10 conda env on my laptop. 
```
conda update stir
```
Unfortunately it pulled the cuda version of STIR even if I don't have a GPU (or at least, no cuda stuff), so I cannot run parallelproj.
```
INFO: Calling parallelproj backprojector
cudaMalloc returned error CUDA driver version is insufficient for CUDA runtime version (code 35), line(57)
```

So at present it looks we still have to force the CPU version. That's not great of course. Also, I don't know how to do it. The following all didn't work
```
conda install stir=cpu
conda install stir+cpu
conda install stir+cpuonly
conda install stir cpuonly
```
where I got some inspiration from https://stackoverflow.com/questions/64685062/specifying-cpu-only-for-pytorch-in-conda-yaml-file but that's pytorch specific it seems

**Comment by KrisThielemans** [comment]
An alternative question is how I'd make sure I would get everything to be able to run the CUDA version on a system with a GPU. (It doesn't seem to be documented for parallelproj either)

**Comment by gschramm** [comment]
Hm, all very confusion. I thought conda would install the correct versions ...

To force a cpu install, can you try
```
conda install 'stir=*=*cpu*'
```

**Comment by KrisThielemans** [comment]
```
conda install 'stir=*=*cpu*'
```
worked on my Windows laptop, but clearly it's not desirable. 

I've tried this on mu Ubuntu VM (where admittedly I had mamba), and it seems almost random:
- I had an env with parallelproj 1.13 (cuda), so did `conda update parallelproj` and it got 1.14 cpu. great!
- Another env had parallelproj 1.14 (cuda) and stir (previous) 5.1.0 (cuda), so I did the following
  1. `conda update stir`  still got its cuda version (presumably because it had parallelproj (cuda))
  2. `conda update parallelproj` didn't do anything. 
  3. `conda remove parallelproj stir` got rid of them
  4. `conda install stir` didn't install parallelproj and got to stir 5.0.2. 
  5. `conda install parallelproj stir` installed parallelproj (cuda) and didn't touch stir.
  6. Created a new env `conda create -n stir5 stir parallelproj matplotlib` but that got the cuda version of both

oh well

> Could it be that this is related to [this line](https://github.com/conda-forge/parallelproj-feedstock/blob/3f25fed8247c316170b672d8f4029bff57d3389c/recipe/meta.yaml#L15) in the parallelproj recipe?

I have no idea but I'd be surprised.

I'm afraid we need the experts again.

**Comment by KrisThielemans** [comment]
Might be worth checking what `pytorch` does. The main difference seems to be they create 3 packages `pytorch`, `pytorch-cpu` and `pytorch-gpu`, see [here](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/c48cd2b9035717ae0e14a4b34ea237380178df18/recipe/meta.yaml#L148). Not sure if that matters though.

(Confusingly the feedstock is called *cpu. presumably historical)

**Comment by KrisThielemans** [comment]
by the way, I nearly installed cuda 12, but stir isn't yet available for that version

**Comment by gschramm** [comment]
> Might be worth checking what `pytorch` does. The main difference seems to be they create 3 packages `pytorch`, `pytorch-cpu` and `pytorch-gpu`, see [here](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/c48cd2b9035717ae0e14a4b34ea237380178df18/recipe/meta.yaml#L148). Not sure if that matters though.
> 
> (Confusingly the feedstock is called *cpu. presumably historical)

I started with two different outputs for `parallelproj`, but the conda-forge experts said it wasn't necessary (since I guess conda should be able to find the "correct" build)

**Comment by gschramm** [comment]
> by the way, I nearly installed cuda 12, but stir isn't yet available for that version

I have cuda 12 running on one machine, and it seems not be a problem (I guess it is backward compatible).

**Comment by gschramm** [comment]
> 
1. I guess part of the problem is that conda caches a lot of things. So it might be a good idea to run
```
conda clean --all
```
to remove all cached packages.

To see whether this is a parallelproj or stir problem, could you also run:
```
conda create -n parallelproj-test -c conda-forge parallelproj
```
on Windows and your Ubuntu VM.

2. I asked for help on gitter again

**Comment by KrisThielemans** [comment]
`conda clean --all` does not make any difference.

`conda create -n parallelproj-test -c conda-forge parallelproj` gives on Windows 10 (miniconda)
```
The following NEW packages will be INSTALLED:                                                                                                                                                                                                     parallelproj       conda-forge/win-64::parallelproj-1.2.14-cuda10.2h9a3eccd_0                                           ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0                                                     vc                 conda-forge/win-64::vc-14.3-hb6edc58_10                                                              vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_10                                                                                                                             
```
trying to "just" install STIR gives a load of packages but the (presumably) relevant ones are
```
 parallelproj       conda-forge/win-64::parallelproj-1.2.14-cuda10.2h9a3eccd_0
 stir               conda-forge/win-64::stir-5.1.0-cuda11.2hc117243_2
```
only `parallelproj` on Ubuntu VM (installed as mamba, but using the `conda` command.)
```
 _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge None
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu None
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.2.0-h65d4601_19 None
  libgomp            conda-forge/linux-64::libgomp-12.2.0-h65d4601_19 None
  parallelproj       conda-forge/linux-64::parallelproj-1.2.14-cpuhd8589cd_0 None
```
`stir` gives cuda (as in vi above)
```
 parallelproj       conda-forge/linux-64::parallelproj-1.2.14-cuda11.1h12f7317_0 None
 stir               conda-forge/linux-64::stir-5.1.0-cuda11.1hffbbe33_2 None
```
When using `mama create ...`, installing only parallejproj gives me the cuda version, and installing `stir` as well.

I cannot make sense of this and have no clue how to debug it

**Comment by gschramm** [comment]
Let's try to understand the resolution of `parallelproj` first. I will create an issue in the feedstock and reach out to some conda-forge guys.

**Comment by gschramm** [comment]
According to the docs of the `mamba` resolver (and also according to @carterbox ), one way to prioritize the cpu variant (or de-prioritize) the cuda variant of stir, is to add a `track_feature` - see [here](https://mamba.readthedocs.io/en/latest/advanced_usage/package_resolution.html) and [here](https://github.com/conda-forge/parallelproj-feedstock/issues/14#issuecomment-1446485554).

sth like this here should de-prioritize the cuda variant in mamba
```
build:
  track_features:
    - cuda_SJASXas  # [cuda_compiler_version != "None"]
```

**Comment by gschramm** [comment]
> Side note, do not track that exact feature (cuda_SJASXas) for your recipe. Generate your own random string.

Is there a recommended way how to do that? 
`cuda_SJASXas` bu hitting random keys on my keyboard ...

**Comment by gschramm** [comment]
@KrisThielemans Thanks to Matthew R Becker, I think I found and fixed the cuda/non-cuda install issue in parallelproj.
In the latest build (1.2.14_*_1), there is a new runtime requirement on the virtual `__cuda` package that should help all resolvers to find the correct versions.

Can you try:
```
mamba install parallelproj
```
on your local (linux) non-cuda systems, to see if the issue is fixed (I don't have a non-cuda linux system right now).

If the issue is indeed fixed for parallelproj, I will submit a PR to the STIR-feedstock as well.

**Comment by KrisThielemans** [comment]
This works on both my Windows and Linux. great!

**Comment by gschramm** [comment]
getting closer to the solution ;), also convergence might be O(1/sqrt(number of PRs))

**Comment by KrisThielemans** [comment]
forgot to close this
